# -*- mode: ruby -*-
# vi: set ft=ruby :

# https://docs.vagrantup.com/v2/
Vagrant.configure(2) do |config|

  # Vagrant box
  config.vm.box = "centos/7"

  # Forwarded Ports
  # config.vm.network "forwarded_port", guest: 8080, host: 8080

  # ansible configurations
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "site.yml"
  end

  # virtualbox settings
  # config.vm.provider "virtualbox" do |vb|
  #   vb.memory = "2048"
  #   vb.cpus = 2
  # end
  
end
