# -*- mode: ruby -*-
# vi: set ft=ruby :

# https://docs.vagrantup.com/v2/
Vagrant.configure(2) do |config|

  # Vagrant box
  config.vm.box = "centos/7"

  # Forwarded Ports
  config.vm.network "forwarded_port", guest: 2181, host: 2181
  config.vm.network "forwarded_port", guest: 9092, host: 9092

  # ansible configurations
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "site.yml"
  end

end
